image: docker:20.10.16

services:
  - docker:20.10.16-dind

before_script:
  - apk --no-cache add nodejs
  - apk --no-cache add npm
  - apk --no-cache add curl
    
stages:
    - build
    - deploy
  
build:dev:
  stage: build
  script:
    - echo "Start build..."
    # Build the container image
    - docker build --build-arg "configuration=development" -t registry.polygram-solutions.com/scholar-admin-dev .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_SERVER
    # Push the container image to the registry
    - docker push registry.polygram-solutions.com/scholar-admin-dev
    # Cleanup by removing the local image
    - docker image rm registry.polygram-solutions.com/scholar-admin-dev

  only:
    - dev

deploy:dev:
  stage: deploy
  script:
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl --kubeconfig=$K8S_TOKEN_DEV get nodes
    # create/update the kubernetes resources
    - kubectl --kubeconfig=$K8S_TOKEN_DEV apply -f k8s-manifest-dev.yml
    # Restart the deployment so as to pull the latest version of the container image
    - kubectl --kubeconfig=$K8S_TOKEN_DEV rollout restart deployment/scholar-admin-dev
  environment:
    name: development
  only:
    - dev
  dependencies:
    - build:dev

build:staging:
  stage: build
  script:
    - echo "Start build..."
    # Build the container image
    - docker build --build-arg "configuration=staging" -t registry.polygram-solutions.com/scholar-admin-stg .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_SERVER
    # Push the container image to the registry
    - docker push registry.polygram-solutions.com/scholar-admin-stg
    # Cleanup by removing the local image
    - docker image rm registry.polygram-solutions.com/scholar-admin-stg

  only:
    - staging

deploy:staging:
  stage: deploy
  script:
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl --kubeconfig=$K8S_TOKEN_TVET get nodes
    # create/update the kubernetes resources
    - kubectl --kubeconfig=$K8S_TOKEN_TVET apply -f k8s-manifest-stg.yml
    # Restart the deployment so as to pull the latest version of the container image
    - kubectl --kubeconfig=$K8S_TOKEN_TVET rollout restart deployment/scholar-admin-stg
  environment:
    name: production
  only:
    - staging
  dependencies:
    - build:staging

build:main:
  stage: build
  script:
    - echo "Start build..."
    # Build the container image
    - docker build --build-arg "configuration=production" -t registry.polygram-solutions.com/scholar-admin .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_SERVER
    # Push the container image to the registry
    - docker push registry.polygram-solutions.com/scholar-admin
    # Cleanup by removing the local image
    - docker image rm registry.polygram-solutions.com/scholar-admin

  only:
    - main

deploy:main:
  stage: deploy
  script:
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl --kubeconfig=$K8S_TOKEN_TVET get nodes
    # create/update the kubernetes resources
    - kubectl --kubeconfig=$K8S_TOKEN_TVET apply -f k8s-manifest.yml
    # Restart the deployment so as to pull the latest version of the container image
    - kubectl --kubeconfig=$K8S_TOKEN_TVET rollout restart deployment/scholar-admin
  environment:
    name: production
  only:
    - main
  dependencies:
    - build:main
