# This section will create a deployment in the Kubernetes clusterscholar-admin-stg
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholar-admin-stg
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: scholar-admin-stg
  template:
    metadata:
      labels:
        app: scholar-admin-stg
    spec:
      containers:
      - name: scholar-admin-stg
        image: registry.polygram-solutions.com/scholar-admin-stg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-secret
---
# This section will create a service in the Kubernetes cluster
# so that the deployment can be accessed from the outside
apiVersion: v1
kind: Service
metadata:
  name: scholar-admin-stg
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: scholar-admin-stg
  type: ClusterIP
